### ISSUE TITLE
Error on Dijkstra precomputer

### ISSUE THREAD

**Issue by ThatDezKnightGuy** [DeloitteDigitalAPAC/LightOSM.jl#1]
There was an issue on line 418 of graph.jl:  `g.dijkstra_states = Vector{U}(undef, n)` with an Int32 to Array{Int32, 1} implicit conversion not being possible. Was this supposed to be as follows?
`g.dijkstra_states = Vector{Vector{U}}(undef, n)`

**Comment by captchanjack** [comment]
Nice spot! This should be fixed with this commit: [5638076](https://github.com/DeloitteDigitalAPAC/LightOSM.jl/commit/5638076f24f4ffc86bcec8bf78456fcc79e9864c)

It's tagged as v0.1.2
