### ISSUE TITLE
Refactor highways to ways in graphs

### ISSUE THREAD

**Issue by spcogg** [DeloitteDigitalAPAC/LightOSM.jl#18]
Currently struct OSMGraphs types.jl has 'highways' as the field, this should be refactored to 'ways' to handle more general types of ways (e.g. rail)

For backwards compatibility, @mmiller-max  proposed to overload the getproperty for the struct, so that when users call g.highway under the hood g.ways will be called instead

**Comment by fbanning** [comment]
This is a good idea. I also found the property name "highways" to be a bit confusing and not general enough.
