### ISSUE TITLE
`shortest_path` throws an error when no path is found

### ISSUE THREAD

**Issue by AayushSabharwal** [DeloitteDigitalAPAC/LightOSM.jl#61]
Currently, the `shortest_path` function throws an error when there is no path from the source to the destination. This makes handling the case where the path doesn't exist require a try-catch block, which isn't good for performance. Can it be refactored to return `nothing` in such a scenario?

**Comment by Datseris** [comment]
Yes please. Throwing error in such cases is very different from Julia's base design of search functions which always return `nothing` if there is no answer found.

**Comment by mmiller-max** [comment]
Yep this makes sense. Will need to be a breaking release so it makes sense to do #45 at the same time.

**Comment by captchanjack** [comment]
Closed by #69
