### ISSUE TITLE
Doc string issues for function `download_osm_network`

### ISSUE THREAD

**Issue by ThatDezKnightGuy** [DeloitteDigitalAPAC/LightOSM.jl#7]
The docstring lists `:bounding_box` as a download_method, but the method needs `:bbox`

**Comment by captchanjack** [comment]
Fixed in commit [b47c81c
](https://github.com/DeloitteDigitalAPAC/LightOSM.jl/commit/b47c81cdc8e237f0045848cbdcc76dd22d60a659)
